local colors = {
-- NORAL&SignColumn bg = #130014
-- PATCH_OPEN
Normal = {fg = "#CC3380", bg = "#0B070D"},
Identifier = {link = "Normal"},
Boolean = {fg = "#D85EED"},
["@boolean"] = {link = "Boolean"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#291533"},
Comment = {fg = "#8D7C87"},
["@comment"] = {link = "Comment"},
["@string.documentation.python"] = {link = "Comment"},
Conceal = {fg = "#574B5D"},
Constant = {fg = "#BC5724"},
["@constant"] = {link = "Constant"},
["@define"] = {link = "Constant"},
CurSearch = {fg = "#0B070D", bg = "#D65CC2"},
Search = {link = "CurSearch"},
Cursor = {fg = "#0B070D", bg = "#D65CC2"},
CursorColumn = {bg = "#261E2A"},
CursorLine = {bg = "#261E2A"},
CursorLineFold = {fg = "#0D1B1C", bg = "#9F2EEA"},
Debug = {fg = "#15AEBC"},
["@debug"] = {link = "Debug"},
DiagnosticError = {fg = "#E14141"},
DiagnosticHint = {fg = "#D65CC2"},
DiagnosticInfo = {fg = "#8E74D8"},
DiagnosticOk = {fg = "#26D959"},
DiagnosticUnderlineError = {sp = "#D03939", undercurl = true},
DiagnosticUnderlineHint = {sp = "#D65CC2", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#9419E6", undercurl = true},
DiagnosticUnderlineOk = {sp = "#26D959", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#E27036", undercurl = true},
DiagnosticWarn = {fg = "#E6E64C"},
DiffAdd = {fg = "#26D959"},
DiffChange = {fg = "#E6E64C"},
DiffDelete = {fg = "#D03939"},
DiffText = {sp = "#E6E64C", undercurl = true},
Directory = {fg = "#9419E6"},
EndOfBuffer = {fg = "#A2396E"},
Error = {fg = "#0B070D", bg = "#D03939"},
ErrorMsg = {fg = "#CF6E6E", bg = "#331524"},
["@float"] = {link = "Float"},
FoldColumn = {fg = "#050A0B", bg = "#7712BA"},
Folded = {fg = "#050A0B", bg = "#7712BA"},
Function = {fg = "#4A64E3"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
IblIndent = {fg = "#A87AA5"},
IblScope = {fg = "#9F7EA5"},
["@namespace"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
["@include"] = {link = "Include"},
IndentBlanklineContextStart = {fg = "#A686B6", sp = "#CC3380", undercurl = true},
IndentBlanklineChar = {link = "IndentBlanklineSpaceCharBlankline"},
IndentBlanklineSpaceChar = {link = "IndentBlanklineSpaceCharBlankline"},
LineNr = {fg = "#E27036"},
CursorLineNr = {link = "LineNr"},
LineNrAbove = {fg = "#C24747"},
LineNrBelow = {link = "LineNrAbove"},
LspReferenceText = {},
NonText = {fg = "#4860D5"},
Number = {fg = "#E27036"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#C7DADC"},
["@operator"] = {link = "Operator"},
["@punctuation"] = {link = "Operator"},
Pmenu = {fg = "#CC3380", bg = "#19111D"},
PmenuKind = {fg = "#E27036"},
PmenuKindSel = {fg = "#EB6D2D", bg = "#A32966"},
PmenuSel = {fg = "#19111D", bg = "#A32966"},
PmenuExtraSel = {link = "PmenuSel"},
PreProc = {fg = "#428A80"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@function.macro"] = {link = "PreProc"},
["@macro"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
QuickFixLine = {fg = "#0B070D", bg = "#9419E6"},
SignColumn = {fg = "#FFFFFF", bg = "#0B070D"},
Special = {fg = "#D03939"},
Delimiter = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpellBad = {sp = "#D03939", undercurl = true},
SpellCap = {sp = "#9419E6", undercurl = true},
SpellLocal = {sp = "#36D4E2", undercurl = true},
SpellRare = {link = "SpellLocal"},
Statement = {fg = "#74BDD8"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
Typedef = {link = "Statement"},
["@conditional"] = {link = "Statement"},
["@exception"] = {link = "Statement"},
["@keyword"] = {link = "Statement"},
["@label"] = {link = "Statement"},
["@repeat"] = {link = "Statement"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#DA8BCD"},
Character = {link = "String"},
["@string"] = {link = "String"},
Structure = {fg = "#9419E6"},
["@lsp.type.class"] = {link = "Structure"},
["@structure"] = {link = "Structure"},
Substitute = {fg = "#0B070D", bg = "#CC3380"},
["@tag"] = {link = "Tag"},
TelescopeSelection = {fg = "#0B070D", bg = "#CC3380"},
Title = {fg = "#BF75F0"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#15AEBC"},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#E26565"},
StorageClass = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {fg = "#D65CC2", underline = true},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#CC3380"},
VimwikiBold = {fg = "#AF2C37"},
Visual = {fg = "#0B070E", bg = "#8E16DF"},
WarningMsg = {fg = "#E6E64C"},
Whitespace = {fg = "#935AAF"},
IndentBlanklineSpaceCharBlankline = {link = "Whitespace"},
WildMenu = {fg = "#0B070D", bg = "#9419E6"},
["@constant.macro"] = {fg = "#9419E6"},
["@constructor"] = {fg = "#C9784F"},
["@field"] = {fg = "#E01FC0"},
["@method.call"] = {fg = "#5A71E2"},
["@lsp.type.mehod"] = {link = "@method"},
["@parameter"] = {fg = "#D03939"},
["@property"] = {fg = "#C355B1"},
["@lsp.type.property"] = {link = "@property"},
["@text.literal"] = {fg = "#309C4F"},
["@text.reference"] = {fg = "#C355B1"},
["@text.underline"] = {undercurl = true},
["@variable.builtin"] = {fg = "#4CDCBD"},
["@lsp.typemod.variable.defaultLibrary"] = {link = "@variable.builtin"},
["@lsp.type.variable"] = {link = "@variable"},
-- PATCH_CLOSE
}

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
