local colors = {
-- NORAL&SignColumn bg = #130014
-- PATCH_OPEN
Normal = {fg = "#CF1782", bg = "#0C020D"},
Identifier = {link = "Normal"},
Boolean = {fg = "#D138FF"},
["@boolean"] = {link = "Boolean"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#2C132F"},
Comment = {fg = "#9B6F82"},
["@comment"] = {link = "Comment"},
["@string.documentation.python"] = {link = "Comment"},
Conceal = {fg = "#643B68"},
Constant = {fg = "#BC5724"},
["@constant"] = {link = "Constant"},
["@define"] = {link = "Constant"},
CurSearch = {fg = "#0C020D", bg = "#8700E0"},
Search = {link = "CurSearch"},
Cursor = {fg = "#0C020D", bg = "#CF1782"},
CursorColumn = {bg = "#2C132F"},
CursorLine = {bg = "#2C132F"},
CursorLineFold = {fg = "#0B1819", bg = "#9900FF"},
Debug = {fg = "#0F9CA9"},
["@debug"] = {link = "Debug"},
DiagnosticError = {fg = "#DF3A3A"},
DiagnosticHint = {fg = "#D78ED7"},
DiagnosticInfo = {fg = "#7B56E1"},
DiagnosticOk = {fg = "#0FBD40"},
DiagnosticUnderlineError = {sp = "#CC3333", undercurl = true},
DiagnosticUnderlineHint = {sp = "#D78ED7", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#8700E0", undercurl = true},
DiagnosticUnderlineOk = {sp = "#0FBD40", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#E27036", undercurl = true},
DiagnosticWarn = {fg = "#E0E052"},
DiffAdd = {fg = "#0FBD40"},
DiffChange = {fg = "#E0E052"},
DiffDelete = {fg = "#CC3333"},
DiffText = {sp = "#E0E052", undercurl = true},
Directory = {fg = "#8700E0"},
EndOfBuffer = {fg = "#9F236B"},
Error = {fg = "#0C020D", bg = "#CC3333"},
ErrorMsg = {fg = "#CA6868", bg = "#3A0815"},
["@float"] = {link = "Float"},
FoldColumn = {fg = "#030707", bg = "#6B00B3"},
Folded = {fg = "#030707", bg = "#6B00B3"},
Function = {fg = "#3750CD"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
IblIndent = {fg = "#692052"},
IblScope = {fg = "#8A3384"},
["@namespace"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
["@include"] = {link = "Include"},
IndentBlanklineContextStart = {fg = "#45114B", sp = "#CF1782", undercurl = true},
IndentBlanklineChar = {link = "IndentBlanklineSpaceCharBlankline"},
IndentBlanklineSpaceChar = {link = "IndentBlanklineSpaceCharBlankline"},
LineNr = {fg = "#E27036"},
CursorLineNr = {link = "LineNr"},
LineNrAbove = {fg = "#BD4242"},
LineNrBelow = {link = "LineNrAbove"},
LspReferenceText = {},
NonText = {fg = "#435CDB"},
Number = {fg = "#E27036"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#D78E9A"},
["@operator"] = {link = "Operator"},
["@punctuation"] = {link = "Operator"},
Pmenu = {fg = "#CF1782", bg = "#1F0821"},
PmenuKind = {fg = "#E27036"},
PmenuKindSel = {fg = "#EB6D2D", bg = "#A51268"},
PmenuSel = {fg = "#1F0821", bg = "#A51268"},
PmenuExtraSel = {link = "PmenuSel"},
PreProc = {fg = "#2F756B"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@function.macro"] = {link = "PreProc"},
["@macro"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
QuickFixLine = {fg = "#0C020D", bg = "#8700E0"},
SignColumn = {fg = "#FFFFFF", bg = "#0C020D"},
Special = {fg = "#CC3333"},
Delimiter = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpellBad = {sp = "#CC3333", undercurl = true},
SpellCap = {sp = "#8700E0", undercurl = true},
SpellLocal = {sp = "#18CCDC", undercurl = true},
SpellRare = {link = "SpellLocal"},
Statement = {fg = "#4CA6EB"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
Typedef = {link = "Statement"},
["@conditional"] = {link = "Statement"},
["@exception"] = {link = "Statement"},
["@keyword"] = {link = "Statement"},
["@label"] = {link = "Statement"},
["@repeat"] = {link = "Statement"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#D78ED7"},
Character = {link = "String"},
["@string"] = {link = "String"},
Structure = {fg = "#8700E0"},
["@lsp.type.class"] = {link = "Structure"},
["@structure"] = {link = "Structure"},
Substitute = {fg = "#0C020D", bg = "#CF1782"},
["@tag"] = {link = "Tag"},
TelescopeSelection = {fg = "#0C020D", bg = "#CF1782"},
Title = {fg = "#BA52FF"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#0F9CA9"},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#E26565"},
StorageClass = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {fg = "#D78ED7", underline = true},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#CF1782"},
VimwikiBold = {fg = "#AE132D"},
Visual = {fg = "#0C020D", bg = "#8100D6"},
WarningMsg = {fg = "#E0E052"},
Whitespace = {fg = "#45114B"},
IndentBlanklineSpaceCharBlankline = {link = "Whitespace"},
WildMenu = {fg = "#0C020D", bg = "#8700E0"},
["@constant.macro"] = {fg = "#8700E0"},
["@constructor"] = {fg = "#C9784F"},
["@field"] = {fg = "#D80EC7"},
["@method.call"] = {fg = "#556EE7"},
["@lsp.type.mehod"] = {link = "@method"},
["@parameter"] = {fg = "#CC3333"},
["@property"] = {fg = "#D232C5"},
["@lsp.type.property"] = {link = "@property"},
["@text.literal"] = {fg = "#1D863B"},
["@text.reference"] = {fg = "#D232C5"},
["@text.underline"] = {undercurl = true},
["@variable.builtin"] = {fg = "#10CB93"},
["@lsp.typemod.variable.defaultLibrary"] = {link = "@variable.builtin"},
["@lsp.type.variable"] = {link = "@variable"},
-- PATCH_CLOSE
}

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
